---
title: "Data Cleaning"
author: "oyogo"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table) # for data wrangling 
library(plotly)   # for data visualization
library(stringi) # package for string manipulation  
library(dplyr) # for data manipulation/wrangling
library(pins) # for data versioning
library(googlesheets4) # fetching data from google sheets  
```

## Data import 
- Use read_sheet function to fetch the data from google sheet.  
- 
```{r} 

gs4_deauth() # this deactivates authentication. We won't be prompted to login using credentials.

kenya_tech_salary.data <- read_sheet("https://docs.google.com/spreadsheets/d/1Ghtm22plhLU2IlxCmzhLSsbhmv2Nsdrci3-OdorC7Ys/edit#gid=901575294")
kenya_tech_salary <- data.table::setDT(kenya_tech_salary.data) # create a datatable object

```

## Data wrangling 
 - Clean the column names; makes it easy. 
 - 
```{r}

## Assign columns names.
names(kenya_tech_salary) <- c('time.stamp','current.role','other.role','role.level',
                              'years.experience','employer.industry','gender','tech.stack',
                              'other.stack','monthly.gross.salary','other.benefits','work.setup',
                              'employer.type') 

## Select needed columns
cols.to.select <- c('current.role','role.level','years.experience','employer.industry','gender',
                    'tech.stack','monthly.gross.salary','other.benefits','work.setup','employer.type')

kenya_tech_salary <- kenya_tech_salary[,..cols.to.select] 

## clean role.level column
### We have 'eg' appearing in 90% of the instances. We could use this to drop all characters following it.
### The 10% records are for interns which don't have the characters 'eg'

kenya_tech_salary <- kenya_tech_salary[,role.level:=sub('eg.*','',role.level)]

## Clean the monthly.income data:
### Spotted some submissions with Kshs and others have commas
### some have other currencies i.e Euros and dollars - need to convert this to Kshs for consistency's sake. 
kenya_tech_salary <- kenya_tech_salary[,monthly.gross.salary:=as.numeric(gsub('^0-9]','',monthly.gross.salary))]

kenya_tech_salary <- kenya_tech_salary[complete.cases(kenya_tech_salary)&monthly.gross.salary>1000]

```

## Best paying industry
```{r}

pay.per.industry <- kenya_tech_salary[,.(average.monthly.salary=mean(monthly.gross.salary)),
                                      by=employer.industry][,.(average.monthly.salary=sort(average.monthly.salary, decreasing = TRUE)),by=employer.industry]

pay.per.industry %>%
  plot_ly(y=~reorder(employer.industry,-average.monthly.salary),
          x=~average.monthly.salary,
          type = "bar") %>%

      layout(title = "Top 20 best paying industries",
             font = list(size=10, family = "Gravitas One"),
             yaxis = list(title = "Average monthly gross salary", tickformat = "Kshs", showgrid=FALSE),
             xaxis = list(title = "Industry", showgrid=FALSE),
             plot_bgcolor  = "rgba(0, 0, 0, 0)",
             paper_bgcolor = "rgba(0, 0, 0, 0)",
             fig_bgcolor   = "rgba(0, 0, 0, 0)"
      )%>%
      config(displayModeBar = FALSE, displaylogo = FALSE, 
             scrollZoom = FALSE, showAxisDragHandles = TRUE, 
             showSendToCloud = FALSE)
```

